const fs = require("node:fs");
const path = require("node:path");
const matter = require("gray-matter");
const MarkdownIt = require("markdown-it");

const ROOT_DIR = path.resolve(__dirname, "..");
const CONTENT_DIR = path.join(ROOT_DIR, "content", "wiki");
const TEMPLATE_PATH = path.join(ROOT_DIR, "wiki", "_template.html");
const OUTPUT_DIR = path.join(ROOT_DIR, "wiki");
const STRUCTURE_PATH = path.join(ROOT_DIR, "data", "wiki-structure.json");
const TOPICS_PATH = path.join(ROOT_DIR, "data", "themen.json");
const GENERATED_MARKER = "<!-- Generated by scripts/build-wiki.js";

const md = new MarkdownIt({
  html: false,
  linkify: true,
  typographer: false
});

const SECTION_IDS = {
  definition: "definition",
  explanation: "erklaerung",
  classification: "einordnung",
  example: "beispiel",
  distinction: "abgrenzung",
  practicalRelevance: "praxisbezug",
  summary: "zusammenfassung",
  usedTerms: "verwendete-begriffe",
  relatedTopics: "aehnliche-themen",
  sources: "verwendete-quellen"
};

const FIELD_LABELS = new Map([
  ["titel", "title"],
  ["slug", "slug"],
  ["kategorie", "category"],
  ["unterkategorie", "subcategory"],
  ["kurzbeschreibung", "description"],
  ["lead", "lead"],
  ["definition", "definition"],
  ["erklaerung", "explanation"],
  ["einordnung", "classification"],
  ["beispiel", "example"],
  ["praxisbezug", "practicalRelevance"],
  ["abgrenzung", "distinction"],
  ["zusammenfassung", "summary"],
  ["verwendete begriffe", "usedTerms"],
  ["ahnliche themen", "relatedTopics"],
  ["aehnliche themen", "relatedTopics"],
  ["quellen", "sources"]
]);

const REQUIRED_FIELDS = [
  "title",
  "slug",
  "category",
  "subcategory",
  "description",
  "lead",
  "explanation",
  "classification",
  "practicalRelevance",
  "summary"
];

const LIST_FIELDS = new Set(["usedTerms", "relatedTopics", "sources"]);

function toAscii(value) {
  return String(value || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\u00df/g, "ss");
}

function normalizeText(value) {
  return String(value || "").replace(/\r\n/g, "\n");
}

function normalizeLabel(value) {
  return toAscii(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

function slugify(value) {
  return toAscii(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function getMarkdownFiles(dir) {
  if (!fs.existsSync(dir)) {
    return [];
  }

  return fs.readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith(".md"))
    .map((entry) => path.join(dir, entry.name))
    .sort((left, right) => left.localeCompare(right, "de"));
}

function readJson(filePath, fallback) {
  if (!fs.existsSync(filePath)) {
    return fallback;
  }

  try {
    return JSON.parse(fs.readFileSync(filePath, "utf8"));
  } catch (error) {
    throw new Error(`JSON-Datei konnte nicht gelesen werden: ${path.relative(ROOT_DIR, filePath)}. ${error.message}`);
  }
}

function writeJson(filePath, value) {
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function readTemplate() {
  return fs.readFileSync(TEMPLATE_PATH, "utf8");
}

function parseListValue(rawValue) {
  const lines = normalizeText(rawValue).split("\n");
  const items = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      continue;
    }

    if (/^[-*]\s+/.test(trimmed)) {
      items.push(trimmed.replace(/^[-*]\s+/, "").trim());
      continue;
    }

    items.push(trimmed);
  }

  return items;
}

function setParsedField(target, key, rawValue) {
  if (!key) {
    return;
  }

  if (LIST_FIELDS.has(key)) {
    target[key] = parseListValue(rawValue);
    return;
  }

  target[key] = normalizeText(rawValue).trim();
}

function parseStructuredFields(raw, filePath) {
  const lines = normalizeText(raw).split("\n");
  const parsed = {};
  let currentKey = null;
  let currentBuffer = [];

  const flush = () => {
    if (!currentKey) {
      return;
    }

    setParsedField(parsed, currentKey, currentBuffer.join("\n"));
    currentKey = null;
    currentBuffer = [];
  };

  for (const line of lines) {
    const match = /^([^:]+):\s*(.*)$/.exec(line);
    const normalizedField = match ? FIELD_LABELS.get(normalizeLabel(match[1])) : null;

    if (normalizedField) {
      flush();
      currentKey = normalizedField;
      currentBuffer.push(match[2] || "");
      continue;
    }

    if (!currentKey) {
      if (line.trim()) {
        throw new Error(`Unerwarteter Inhalt vor dem ersten Feld in ${path.relative(ROOT_DIR, filePath)}.`);
      }
      continue;
    }

    currentBuffer.push(line);
  }

  flush();
  return parsed;
}

function splitMarkdownSections(content) {
  const lines = normalizeText(content).split("\n");
  const introLines = [];
  const sections = [];
  let current = null;
  let hasSection = false;

  for (const line of lines) {
    const match = /^##\s+(.+?)\s*$/.exec(line);
    if (match) {
      hasSection = true;
      if (current) {
        sections.push(current);
      }
      current = { heading: match[1].trim(), lines: [] };
      continue;
    }

    if (!hasSection) {
      introLines.push(line);
      continue;
    }

    if (current) {
      current.lines.push(line);
    }
  }

  if (current) {
    sections.push(current);
  }

  return {
    intro: introLines.join("\n").trim(),
    sections: sections.map((section) => ({
      key: mapHeadingToField(section.heading),
      heading: section.heading,
      markdown: section.lines.join("\n").trim()
    }))
  };
}

function mapHeadingToField(heading) {
  const mapped = FIELD_LABELS.get(normalizeLabel(heading));
  if (!mapped || ["title", "slug", "category", "subcategory", "description", "lead"].includes(mapped)) {
    return null;
  }
  return mapped;
}

function parseFrontmatterArticle(raw, filePath) {
  const parsed = matter(raw);
  const split = splitMarkdownSections(parsed.content);
  const article = {
    title: String(parsed.data.title || "").trim(),
    slug: String(parsed.data.slug || "").trim(),
    category: String(parsed.data.category || "").trim(),
    subcategory: String(parsed.data.subcategory || "").trim(),
    description: String(parsed.data.description || "").trim(),
    lead: split.intro || String(parsed.data.lead || "").trim()
  };

  for (const section of split.sections) {
    if (!section.markdown) {
      continue;
    }

    if (!section.key) {
      throw new Error(`Unbekannte Abschnittsueberschrift "${section.heading}" in ${path.relative(ROOT_DIR, filePath)}.`);
    }

    if (LIST_FIELDS.has(section.key)) {
      article[section.key] = parseListValue(section.markdown);
    } else {
      article[section.key] = section.markdown.trim();
    }
  }

  return article;
}

function parseSourceFile(filePath) {
  const raw = fs.readFileSync(filePath, "utf8");
  const article = raw.trimStart().startsWith("---")
    ? parseFrontmatterArticle(raw, filePath)
    : parseStructuredFields(raw, filePath);

  article.sourcePath = filePath;
  validateArticle(article);
  return article;
}

function validateArticle(article) {
  for (const field of REQUIRED_FIELDS) {
    if (!String(article[field] || "").trim()) {
      throw new Error(`Pflichtfeld "${field}" fehlt in ${path.relative(ROOT_DIR, article.sourcePath)}.`);
    }
  }
}

function assertSafeOutputTarget(outputPath) {
  if (!fs.existsSync(outputPath)) {
    return;
  }

  const existing = fs.readFileSync(outputPath, "utf8");
  if (!existing.includes(GENERATED_MARKER)) {
    throw new Error(`Zieldatei ${path.relative(ROOT_DIR, outputPath)} existiert bereits und wird nicht ueberschrieben, weil sie nicht vom Wiki-Build erzeugt wurde.`);
  }
}

function renderMarkdown(markdown) {
  return md.render(normalizeText(markdown).trim());
}

function renderDefinitionSection(markdown) {
  if (!markdown) {
    return "";
  }

  return `          <section aria-labelledby="${SECTION_IDS.definition}">
            <h2 id="${SECTION_IDS.definition}">Definition</h2>
            <div class="definition-box">
              ${renderMarkdown(markdown).trim()}
              <button type="button" class="copy-definition" title="Definition kopieren" aria-label="Definition kopieren">Kopieren</button>
            </div>
          </section>`;
}

function renderStandardSection(id, title, markdown) {
  if (!markdown) {
    return "";
  }

  return `          <section aria-labelledby="${id}">
            <h2 id="${id}">${title}</h2>
            ${renderMarkdown(markdown).trim()}
          </section>`;
}

function renderResolvedLinkList(id, title, items, lookup, mode) {
  const resolved = (items || [])
    .map((item) => resolveArticleReference(item, lookup, mode))
    .filter(Boolean);

  if (!resolved.length) {
    return "";
  }

  const listItems = resolved.map((item) => {
    if (item.href) {
      return `              <li><a href="${escapeHtml(item.href)}">${escapeHtml(item.label)}</a></li>`;
    }
    return `              <li>${escapeHtml(item.label)}</li>`;
  }).join("\n");

  return `          <section aria-labelledby="${id}">
            <h2 id="${id}">${title}</h2>
            <ul class="link-list">
${listItems}
            </ul>
          </section>`;
}

function renderSourcesSection(items) {
  const normalized = (items || [])
    .map((item) => normalizeSourceItem(item))
    .filter(Boolean);

  if (!normalized.length) {
    return "";
  }

  const listItems = normalized.map((item) => {
    if (item.href) {
      return `              <li><a href="${escapeHtml(item.href)}" target="_blank" rel="noopener noreferrer">${escapeHtml(item.label)}</a></li>`;
    }
    return `              <li>${escapeHtml(item.label)}</li>`;
  }).join("\n");

  return `          <section aria-labelledby="${SECTION_IDS.sources}">
            <h2 id="${SECTION_IDS.sources}">Verwendete Quellen</h2>
            <ul class="link-list">
${listItems}
            </ul>
          </section>`;
}

function normalizeSourceItem(item) {
  const value = String(item || "").trim();
  if (!value) {
    return null;
  }

  const pipeMatch = /^(.+?)\s*\|\s*(https?:\/\/\S+)$/i.exec(value);
  if (pipeMatch) {
    return { label: pipeMatch[1].trim(), href: pipeMatch[2].trim() };
  }

  if (/^https?:\/\/\S+$/i.test(value)) {
    return { label: value, href: value };
  }

  return { label: value };
}

function resolveArticleReference(value, lookup, mode) {
  const raw = String(value || "").trim();
  if (!raw) {
    return null;
  }

  const normalized = normalizeLabel(raw);
  const slug = slugify(raw);
  const match = lookup.get(normalized) || lookup.get(slug);

  if (match) {
    return {
      label: match.title,
      href: `./${match.slug}.html`
    };
  }

  if (mode === "related" && slug && fs.existsSync(path.join(OUTPUT_DIR, `${slug}.html`))) {
    return {
      label: raw,
      href: `./${slug}.html`
    };
  }

  return {
    label: raw
  };
}

function renderOptionalCard(className, ariaLabel, sections) {
  const content = sections.filter(Boolean).join("\n");
  if (!content) {
    return "";
  }

  return `
        <section class="card wiki-article-card ${className}" aria-label="${ariaLabel}">
${content}
        </section>`;
}

function renderArticle(article, lookup) {
  const foundationSections = [
    renderDefinitionSection(article.definition),
    renderStandardSection(SECTION_IDS.explanation, "Erklaerung", article.explanation),
    renderStandardSection(SECTION_IDS.classification, "Einordnung", article.classification)
  ];

  const applicationSections = [
    renderStandardSection(SECTION_IDS.example, "Beispiel", article.example),
    renderStandardSection(SECTION_IDS.distinction, "Abgrenzung", article.distinction),
    renderStandardSection(SECTION_IDS.practicalRelevance, "Praxisbezug", article.practicalRelevance)
  ];

  const summarySection = renderStandardSection(SECTION_IDS.summary, "Zusammenfassung", article.summary);

  return `${GENERATED_MARKER} from ${path.relative(ROOT_DIR, article.sourcePath)}; do not edit directly. -->
      <article class="wiki-article" aria-labelledby="article-title">
        <section class="card wiki-article-card wiki-article-card-intro">
          <div class="wiki-article-header">
            <h1 id="article-title">${escapeHtml(article.title)}</h1>
            <p class="lead">${escapeHtml(article.lead)}</p>
          </div>
        </section>
${renderOptionalCard("wiki-article-card-foundation", "Wissensbasis", foundationSections)}
${renderOptionalCard("wiki-article-card-application", "Anwendung und Differenzierung", applicationSections)}
${renderOptionalCard("wiki-article-card-summary", "Zusammenfassung", [summarySection])}
${renderOptionalCard("wiki-article-card-network", "Begriffsnetz und Weiterfuehrung", [
    renderResolvedLinkList(SECTION_IDS.usedTerms, "Verwendete Begriffe", article.usedTerms, lookup, "term"),
    renderResolvedLinkList(SECTION_IDS.relatedTopics, "Aehnliche Themen", article.relatedTopics, lookup, "related")
  ])}
${renderOptionalCard("wiki-article-card-sources", "Verwendete Quellen", [
    renderSourcesSection(article.sources)
  ])}
      </article>`;
}

function fillTemplate(template, articleHtml, article) {
  return template
    .replace(/\[Artikeltitel\]/g, escapeHtml(article.title))
    .replace("[Kurze sachliche Beschreibung des Artikels in einem Satz.]", escapeHtml(article.description))
    .replace(/<article class="wiki-article"[\s\S]*?<\/article>/, articleHtml);
}

function buildStructure(articles) {
  const structure = {};

  for (const article of articles) {
    if (!structure[article.category]) {
      structure[article.category] = {};
    }
    if (!structure[article.category][article.subcategory]) {
      structure[article.category][article.subcategory] = [];
    }

    structure[article.category][article.subcategory].push({
      title: article.title,
      slug: article.slug,
      description: article.description
    });
  }

  const sorted = {};
  for (const category of Object.keys(structure).sort((left, right) => left.localeCompare(right, "de"))) {
    sorted[category] = {};
    for (const subcategory of Object.keys(structure[category]).sort((left, right) => left.localeCompare(right, "de"))) {
      sorted[category][subcategory] = structure[category][subcategory]
        .sort((left, right) => left.title.localeCompare(right.title, "de"));
    }
  }

  return sorted;
}

function buildLookup(articles) {
  const lookup = new Map();
  const add = (title, slug) => {
    if (!title || !slug) {
      return;
    }
    const entry = { title, slug };
    lookup.set(normalizeLabel(title), entry);
    lookup.set(slugify(slug), entry);
  };

  const existingTopics = readJson(TOPICS_PATH, []);
  existingTopics.forEach((topic) => add(topic.titel, topic.id || topic.artikelPfad || topic.titel));
  articles.forEach((article) => add(article.title, article.slug));

  for (const [key, value] of Array.from(lookup.entries())) {
    if (value.slug.includes("/")) {
      const fileName = value.slug.split("/").pop() || value.slug;
      lookup.set(key, {
        title: value.title,
        slug: fileName.replace(/\.html$/i, "")
      });
    }
  }

  return lookup;
}

function build() {
  const template = readTemplate();
  const files = getMarkdownFiles(CONTENT_DIR);
  const articles = files.map((filePath) => parseSourceFile(filePath));
  const lookup = buildLookup(articles);

  for (const article of articles) {
    const outputPath = path.join(OUTPUT_DIR, `${article.slug}.html`);
    assertSafeOutputTarget(outputPath);
    const articleHtml = renderArticle(article, lookup);
    const finalHtml = fillTemplate(template, articleHtml, article);
    fs.writeFileSync(outputPath, finalHtml, "utf8");
  }

  writeJson(STRUCTURE_PATH, buildStructure(articles));
  console.log(`Wiki-Build abgeschlossen: ${articles.length} Markdown-Datei(en) verarbeitet.`);
}

build();
